# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tfswihistory
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Jest GitHub Action
      # You may pin to the exact commit or the version.
      # uses: willcaul/jest-github-action@1530da6bb81a1593734e7f175bd872f992f0882e
        uses: willcaul/jest-github-action@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The test command to run
          #test-command: # optional, default is npm test
          # Subdirectory to run tests in
          working-directory: ./tfswihistory
          # Comment PRs with code coverage
          #coverage-comment: # optional, default is true
          # Only run tests on changed files (over base branch)
          #changes-only: # optional, default is false

          
