name: Chrome Addon Action
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Alexey Totmakov'
      home:
        description: 'location'
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Chrome Addon Action
        # You may pin to the exact commit or the version.
        # uses: trmcnvn/chrome-addon@7fc5a5ad3ff597dc64d6a13de7dcaa8515328be7
        uses: trmcnvn/chrome-addon@v2
        with:
          # ID of the extension that you are updating
          extension: ociekhbkajgbjdenikmandhpjlekckee
          # Path to a .zip of your addon
          zip: build/tfswihistory.zip
