name: zip
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Alexey Totmakov'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r tfswihistory.zip ./tfswihistory -x ".git/*" ".github/*"
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v2
      with:
        name: tfswihistory
        path: tfswihistory.zip
