name: zip
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Alexey Totmakov'
      home:
        description: 'location'
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Easy Zip Files
        # You may pin to the exact commit or the version.
        # uses: papeloto/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
        uses: papeloto/action-zip@v1
        with:
          # Files or directories to zip
          files: tfswihistory
